concesionario/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from concesionario import settings
from django.conf.urls.static import static

urlpatterns = [

	url(r'^admin/', admin.site.urls),
    url(r'', include(('apps.inicio.url','inicio'),namespace='inicio')),
    url(r'', include(('apps.cuenta.url','cuenta'),namespace='cuenta')),
    url(r'', include(('apps.cotizacion.url','cotizacion'),namespace='cotizacion')),
    url(r'', include(('apps.cliente.url','cliente'),namespace='cliente')),
    url(r'', include(('apps.empleado.url','empleado'),namespace='empleado')),
    url(r'', include(('apps.repuesto.url','repuesto'),namespace='repuesto')),
    url(r'', include(('apps.sucursal.url','sucursal'),namespace='sucursal')),
    url(r'', include(('apps.vehiculo.url','vehiculo'),namespace='vehiculo')),
    url(r'', include(('apps.venta.url','venta'),namespace='venta')),
    url(r'', include(('apps.proveedor.url','proveedor'),namespace='proveedor')),
    url(r'', include(('apps.reporte.url','reporte'),namespace='reporte')),
    url(r'', include(('apps.orden_de_trabajo.url','orden_de_trabajo'),namespace='orden_de_trabajo')),
    url(r'', include(('apps.cotizacion_orden_de_trabajo.url','cotizacion_orden_de_trabajo'),namespace='cotizacion_orden_de_trabajo')),
	url(r'', include(('apps.factura_orden_de_trabajo.url','factura_orden_de_trabajo'),namespace='factura_orden_de_trabajo')),
    url(r'', include(('apps.movil.url','movil'),namespace='movil')),

    #url para acceder a la imagenes que estan en la carpeta media del proyecto
    #se deseas colocar imagenes en tu contenido HTML, este link es necesario para que se muestren las imagenes
   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/orden_de_trabajo/models.py
# -*- encoding: utf-8 -*-

from django.db import models
from .validators import validador_placa
from apps.empleado.models import Empleado
from apps.cliente.models import Cliente
from apps.sucursal.models import Sucursal
from apps.vehiculo.models import Vehiculo


#Estados de la reparacion del vehiculo

#El vehiculo esta en el taller, pero no se ha revisado
PENDIENTE = 'Pendiente'
#Ya esta la cotización de los daños del vehiculo
COTIZADO = 'Cotizado'
#El vehiculo esta reparado
REPARADO = 'Reparado'
#El vehiuclo fue reparado y entregado al cliente
REPARADO_Y_ENTREGADO = 'Reparado y entregado'
#El vehiculo fue retirado ya que el cliente no acepto su reparacion
RETIRADO = 'Retirado'

tipo_choice = (
	(PENDIENTE, 'Pendiente'),
	(COTIZADO, 'Cotizado'),
	(REPARADO, 'Reparado'),
	(REPARADO_Y_ENTREGADO, 'Reparado y entregado'),
	(RETIRADO, 'Retirado'),
 )

class OrdenDeTrabajo(models.Model):
	"""Define la organizacion del los datos de una orden de trabajo en la base de datos."""

	#Empleado que realiza la orden de trabajo, relacion uno a muchos
	empleado = models.ForeignKey(Empleado,on_delete=models.CASCADE)
	#Sucursal a la que ingresa el vehiculo
	sucursal = models.ForeignKey(Sucursal,on_delete=models.CASCADE)
	#dueno del auto que entra al taller, relacion uno a muchos
	cliente = models.ForeignKey(Cliente,on_delete=models.CASCADE)
	#vehiculo que va a ser reparado
	vehiculo = models.ForeignKey(Vehiculo,on_delete=models.CASCADE)
	#placa del vehiculo que entra al taller
	placa = models.CharField(validators=[validador_placa],max_length=7)
	#Fecha de entrada al taller
	fecha_entrada = models.DateField(auto_now_add=True)
	#Fecha de salida del taller
	fecha_salida = models.DateField(null=True)
	#Estado del vehiculo en el taller
	estado_reparacion = models.TextField(max_length=50,choices=tipo_choice,default=PENDIENTE)
	#Observacion de los daños del vehiculo
	observacion = models.TextField(max_length=200)
	#Estado de la OrdenDeTrabajo, Activa/inactiva
	habilitado = models.BooleanField(default = True)

	#Permite hacer modificaciones agregadas a la representacion del modelo
	class Meta:
		ordering = ['fecha_entrada']
		verbose_name_plural = "Orden de Trabajo"
		unique_together = ('placa','fecha_salida')

	#Permite determinar una representacion en string del objeto repuesto
	def __str__(self):
		return self.vehiculo.marca

	#Permite determinar una represetacion en string para el objeto (Esto es para versiones de Python 2)
	def __unicode__(self):
		return self.vehiculo.marca

apps/orden_de_trabajo/forms.py
# -*- encoding: utf-8 -*-

from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic.edit import UpdateView
from django.contrib import messages
from .models import OrdenDeTrabajo
from .models import RETIRADO
from .models import REPARADO_Y_ENTREGADO
from apps.cliente.models import Cliente
from apps.vehiculo.models import Vehiculo
from apps.inicio.mixins import LoginRequiredMixin

class OrdenDeTrabajoCreateView(LoginRequiredMixin, CreateView):
	model = OrdenDeTrabajo
	fields = [
	'sucursal','empleado','cliente',
	'vehiculo','placa','observacion']
	success_url = reverse_lazy('orden_de_trabajo:listar')
	template_name = 'orden_de_trabajo/form.html'

	def post(self,request,*args,**kwargs):
		form = self.get_form(self.get_form_class())
		if form.is_valid():
			placa = form.cleaned_data['placa']
			ordenes_de_trabajo = OrdenDeTrabajo.objects.filter(placa=placa,fecha_salida=None)
			if ordenes_de_trabajo:
				messages.info(request,"El vehiculo con placa {} ya tiene una orden de trabajo".format(placa))
				return self.get(request,args,kwargs)
			else:
				return super(OrdenDeTrabajoCreateView,self).post(request,args,kwargs)
		else:
			return super(OrdenDeTrabajoCreateView,self).post(request,args,kwargs)

	def get_context_data(self,**kwargs):
		context = super(OrdenDeTrabajoCreateView,self).get_context_data(**kwargs)
		context['section_title'] = 'Nueva Orden de Trabajo'
		context['vehiculos'] = Vehiculo.objects.all()
		context['clientes'] = Cliente.objects.all()
		return context

	def get_initial(self):
		initial = super(OrdenDeTrabajoCreateView,self).get_initial()
		initial = initial.copy()
		initial['sucursal'] = self.request.user.empleado.sucursal
		initial['empleado'] = self.request.user.empleado
		return initial


class OrdenDeTrabajoUpdateView(LoginRequiredMixin, UpdateView):
	model = OrdenDeTrabajo
	fields = fields = [
	'sucursal','empleado','cliente',
	'vehiculo','placa','observacion',
	'habilitado']
	success_url = reverse_lazy('orden_de_trabajo:listar')
	template_name = 'orden_de_trabajo/form.html'

	def get_context_data(self,**kwargs):
		context = super(OrdenDeTrabajoUpdateView,self).get_context_data(**kwargs)
		context['section_title'] = 'Actualizar Orden de Trabajo'
		context['vehiculos'] = Vehiculo.objects.all()
		context['clientes'] = Cliente.objects.all()
		return context

apps/orden_de_trabajo/views.py
# -*- encoding: utf-8 -*-

from django.views.generic import TemplateView
from django.http import HttpResponseRedirect
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.contrib import messages
from django.core.exceptions import ObjectDoesNotExist
from .models import OrdenDeTrabajo
from .models import PENDIENTE
from .models import COTIZADO
from .models import REPARADO
from .models import RETIRADO
from .models import REPARADO_Y_ENTREGADO
from .models import OrdenDeTrabajo
from apps.sucursal.models import Sucursal
from apps.empleado.models import Empleado
from apps.cotizacion_orden_de_trabajo.models import CotizacionOrdenDeTrabajo
from apps.factura_orden_de_trabajo.models import FacturaOrdenDeTrabajo
from datetime import datetime
from apps.inicio.mixins import LoginRequiredMixin

class OrdenDeTrabajoListView(LoginRequiredMixin, ListView):
	model = OrdenDeTrabajo
	context_object_name = 'ordenes_de_trabajo'
	template_name = 'orden_de_trabajo/list.html'

	def get_queryset(self):
		empleado = Empleado.objects.get(id=self.request.user.empleado.id)
		return OrdenDeTrabajo.objects.filter(empleado=empleado,estado_reparacion=PENDIENTE)

	def get_context_data(self):
		context = super(OrdenDeTrabajoListView,self).get_context_data()
		empleado = Empleado.objects.get(id=self.request.user.empleado.id)

		# Se listan las cotizaciones de las ordenes de trabajo, con el fin de mostrar
		# en el template las ordenes de trabajo cuyas repeparaciones han sido cotizadas
		context['cotizaciones'] = CotizacionOrdenDeTrabajo.objects.filter(
			orden_de_trabajo__empleado=empleado,
			orden_de_trabajo__estado_reparacion=COTIZADO
		)

		# Se listan las facturas de las ordenes de trabajo, con el fin de mostrar
		# en el template las ordenes de trabajo facturadas
		context['facturas'] = FacturaOrdenDeTrabajo.objects.filter(
			cotizacion__orden_de_trabajo__empleado=empleado,
			cotizacion__orden_de_trabajo__estado_reparacion=REPARADO
		)

		# Se listan las ordenes de trabajo que han sido realizadas y cuyos vehiculos
		# han sido entregados a sus respectivos clientes
		context['reparados_entregados'] = OrdenDeTrabajo.objects.filter(
			empleado=empleado,
			estado_reparacion=REPARADO_Y_ENTREGADO
		)

		# Se listan las ordenes de trabajo que cuya reparacion no fue efectuada
		# ya que el cliente retiro el vehiuclo
		context['retirados'] = OrdenDeTrabajo.objects.filter(
			empleado=empleado,
			estado_reparacion=RETIRADO
		)
		return context


class RetirarEntregarVehiculoTemplateView(LoginRequiredMixin, TemplateView):

	def get(self,request,*args,**kwargs):
		orden_de_trabajo = OrdenDeTrabajo.objects.get(id=kwargs['pk'])
		try:
			# Si la orden de trabajo, no tiene cotizacion o
			# si tiene cotziacion y no tiene factura, se genera
			# una exepcion al hacer el siguiente llamado
			# orden_de_trabajo.cotizacion.factura
			orden_de_trabajo.cotizacion.factura

			# En el caso de que no se lance la excepcion entonces el
			# vehiculo tiene cotizacion y factura, por lo tanto ya fue
			# reparado y se cambia el estado de la cotizacion a
			# REPARADO_Y_ENTREGADO al momento de ser retirado
			orden_de_trabajo.estado_reparacion = REPARADO_Y_ENTREGADO
			messages.info(request,'El vehiculo fue entregado con exito')
		except ObjectDoesNotExist:
			orden_de_trabajo.estado_reparacion = RETIRADO
			messages.info(request,'El vehiculo fue retirado con exito')

		orden_de_trabajo.fecha_salida = datetime.now().date()
		orden_de_trabajo.save()

		return HttpResponseRedirect(reverse_lazy('orden_de_trabajo:listar'))

apps/orden_de_trabajo/templates/orden_de_trabajo/form.html
{% extends "base.html" %}
{% load static %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}
    <link href="{% static 'color_admin/assets/plugins/bootstrap-wizard/css/bwizard.min.css' %}" rel="stylesheet" />
    <link href="{% static 'color_admin/assets/plugins/DataTables-1.9.4/css/data-table.css' %}" rel="stylesheet" />
{% endblock %}

{% block breadcrumb %}
Gestión Ordenes de Trabajo
{% endblock %}
{% block section_title %}{{ section_title }}{% endblock %}
{% block section_subtitle %}Diligencie el siguiente formulario{% endblock %}
{% block content %}
          <!-- begin col-12 -->
          <div class="col-md-12">
            <form method="POST" data-parsley-validate="true" name="form-wizard" enctype="multipart/form-data"> {% csrf_token %}
              <!-- begin panel -->
                    <div class="panel panel-inverse">
                        <div class="panel-heading">
                            <div class="panel-heading-btn">
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                            </div>
                            <h4 class="panel-title">Orden de Trabajo</h4>
                        </div>
                        <div class="panel-body">
                          <div id="wizard">
                            <ol>
                              <li id="step-1" >
                                  Cliente
                                  <small>Seleccione el cliente para la orden de trabajo</small>
                              </li>
                              <li id="step-2" >
                                  Vehículo
                                  <small>Seleccione el vehículo para la orden de trabajo.</small>
                              </li>
                              <li id="step-3" >
                                  Orden de Trabajo
                                  <small>Complete el formulario de orden de trabao.</small>
                              </li>
                            </ol>
                            <!-- begin wizard step-1 -->
                            <div>
                              <fieldset>
                                  <!-- begin row -->
                                  <div class="row">
                                      {% include 'orden_de_trabajo/includes/tabla_clientes.html' %}
                                  </div>
                                  <!-- end row -->
                              </fieldset>
                            </div>
                            <!-- end wizard step-1 -->
                            <!-- begin wizard step-2 -->
                            <div>
                              <fieldset>
                                <!-- begin row -->
                                <div class="row">
                                      {% include 'orden_de_trabajo/includes/tabla_vehiculos.html' %}
                                </div>
                                <!-- end row -->
                              </fieldset>
                            </div>
                            <!-- end wizard step-2 -->
                            <!-- begin wizard step-3 -->
                            <div>
                              <fieldset>
                                <!-- begin row -->
                                <div class="row">
                                    <div class="col-md-8 col-md-offset-2">
                                        {% bootstrap_form form %}
                                        <div class="pull-right" >
                                            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-cog"></i> Guardar</button>
                                        </div>
                                    </div>
                                </div>
                                <!-- end row -->
                              </fieldset>
                            </div>
                            <!-- end wizard step-3 -->
                          </div>
                        </div>

                    </div>
                <!-- end panel -->
                </form>
            </div>
    <!-- end col-12 -->
{% endblock %}

{% block javascript %}
{{ block.super }}
<script src="{% static 'color_admin/assets/plugins/parsley/dist/parsley.js' %}"></script>
<script src="{% static 'color_admin/assets/plugins/bootstrap-wizard/js/bwizard.js' %}"></script>
<script src="{% static 'color_admin/assets/js/form-wizards-validation.demo.min.js' %}"></script>
<script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/data-table.js' %}"></script>
<script type="text/javascript">
    $(document).ready(function() {
        FormWizardValidation.init();
        $('.table').DataTable();
        {# If the form has errors, the step 3 wizard is showed #}
        {% if form.is_bound and not form.is_valid  %}
            $( "#step-3" ).click();
        {% endif %}
    });
</script>
<script type="text/javascript">
    $( ".vehiculo" ).click(function(event){
        event.preventDefault();
        var clickedVehicleId = $(this).attr('href').split("/")[2];
        $( "#id_vehiculo" ).val(clickedVehicleId);
        $( ".next" ).click();
    });
    $( ".cliente" ).click(function(event){
        event.preventDefault();
        var clickedVehicleId = $(this).attr('href').split("/")[2];
        $( "#id_cliente" ).val(clickedVehicleId);
        $( ".next" ).click();
    });
</script>
{% endblock %}