concesionario/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from concesionario import settings
from django.conf.urls.static import static

urlpatterns = [

	url(r'^admin/', admin.site.urls),
    url(r'', include(('apps.inicio.url','inicio'),namespace='inicio')),
    url(r'', include(('apps.cuenta.url','cuenta'),namespace='cuenta')),
    url(r'', include(('apps.cotizacion.url','cotizacion'),namespace='cotizacion')),
    url(r'', include(('apps.cliente.url','cliente'),namespace='cliente')),
    url(r'', include(('apps.empleado.url','empleado'),namespace='empleado')),
    url(r'', include(('apps.repuesto.url','repuesto'),namespace='repuesto')),
    url(r'', include(('apps.sucursal.url','sucursal'),namespace='sucursal')),
    url(r'', include(('apps.vehiculo.url','vehiculo'),namespace='vehiculo')),
    url(r'', include(('apps.venta.url','venta'),namespace='venta')),
    url(r'', include(('apps.proveedor.url','proveedor'),namespace='proveedor')),
    url(r'', include(('apps.reporte.url','reporte'),namespace='reporte')),
    url(r'', include(('apps.orden_de_trabajo.url','orden_de_trabajo'),namespace='orden_de_trabajo')),
    url(r'', include(('apps.cotizacion_orden_de_trabajo.url','cotizacion_orden_de_trabajo'),namespace='cotizacion_orden_de_trabajo')),
	url(r'', include(('apps.factura_orden_de_trabajo.url','factura_orden_de_trabajo'),namespace='factura_orden_de_trabajo')),
    url(r'', include(('apps.movil.url','movil'),namespace='movil')),

    #url para acceder a la imagenes que estan en la carpeta media del proyecto
    #se deseas colocar imagenes en tu contenido HTML, este link es necesario para que se muestren las imagenes
   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/cotizacion/models.py
# -*- encoding: utf-8 -*-
from django.db import models
from datetime import datetime
from apps.empleado.models import Empleado
from apps.cliente.models import Cliente
from apps.vehiculo.models import Vehiculo


# Forma de pago en que se realiza la compra
CREDITO = 'Credito'
EFECTIVO = 'Efectivo'
TARJETA_CREDITO = 'Tarjeta_credito'
TARJETA_DEBITO = 'Tarjeta_debito'

forma_pago_choices = (
	(CREDITO, 'Credito'),
	(EFECTIVO, 'Efectivo'),
	(TARJETA_CREDITO, 'Tarjeta de credito'),
	(TARJETA_DEBITO, 'Tarjeta de debito'),
)

#
class Cotizacion(models.Model):
	"""Define la organizacion del los datos de una cotizacion en la base de datos."""

	#Empleado que realiza la cotizacion, relacion uno a muchos
	empleado= models.ForeignKey(Empleado,on_delete=models.CASCADE)
	#Cliente que solicita la cotizacion, relacion uno a muchos
	cliente= models.ForeignKey(Cliente,on_delete=models.CASCADE)
	#Vehiculo cotizado, relacion uno a muchos
	vehiculo= models.ForeignKey(Vehiculo,on_delete=models.CASCADE)
	#Fecha en que se realiza la cotizacion
	fecha=models.DateField(auto_now_add=True)
	#Fecha de vencimiento de la cotizacion
	fecha_vencimiento=models.DateField()
	#Forma de pago en la que se realiza la cotizacion
	forma_pago = models.CharField(max_length=20,choices=forma_pago_choices, default=EFECTIVO)
	#Estado de la cotizacion, Activa/inactiva
	habilitado = models.BooleanField(default = True)

	#Permite hacer modificaciones agregadas a la representacion del modelo
	class Meta:
		ordering = ['fecha']
		verbose_name_plural = "Cotizaciones"

	#Permite determinar una representacion en string del objeto
	def __str__(self):
		return self.forma_pago

	#Permite determinar una represetacion en string para el objeto (Esto es para versiones de Python 2)
	def __unicode__(self):
		return self.fecha

apps/cotizacion/forms.py
# -*- encoding: utf-8 -*-
from django.urls import reverse_lazy, reverse
from django import forms
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template import RequestContext
from django.views.generic.edit import CreateView, UpdateView
from .models import Cotizacion
from apps.cliente.models import Cliente
from apps.empleado.models import Empleado
from apps.vehiculo.models import Vehiculo
from django.contrib import messages
from apps.inicio.mixins import LoginRequiredMixin

class CrearCotizacion(LoginRequiredMixin,CreateView):
	fecha_vencimiento=forms.DateField(
		widget=forms.widgets.DateInput(format="%y-%m-%d"))
	model = Cotizacion
	fields = [ 'cliente', 'vehiculo', 'fecha_vencimiento', 'forma_pago']

	def get_context_data(self,**kwargs):

		context = super(CrearCotizacion,self).get_context_data(**kwargs)
		context['search_button_text'] = 'Completar Formulario'

		clientes = Cliente.objects.all()
		context['lista_clientes'] = clientes

		vehiculos = Vehiculo.objects.all()
		context['vehiculos'] = vehiculos

		return context

	def post(self, request, *args, **kwargs):

		empleado = Empleado.objects.get(user_id=self.request.user.id)
		cliente = Cliente.objects.get(pk=request.POST["cliente"])
		vehiculo = Vehiculo.objects.get(pk=request.POST["vehiculo"])
		forma_pago = request.POST["forma_pago"]
		fecha_vencimiento=  request.POST["fecha_vencimiento"]
		print (fecha_vencimiento)
		cotizacion = Cotizacion(empleado = empleado, cliente = cliente, vehiculo = vehiculo, fecha_vencimiento=fecha_vencimiento,forma_pago = forma_pago)
		cotizacion.save()
		context = {'cotizacion':cotizacion}
		return render(request, 'cotizacion/cotizacionPDF.html', context)

class ActualizarCotizacion(LoginRequiredMixin, UpdateView):
	model = Cotizacion
	fields = ['empleado', 'cliente', 'vehiculo', 'fecha','fecha_vencimiento', 'forma_pago']
	def get_success_url(self):
		messages.info(self.request,"Cotización creada con exito")
		return  reverse_lazy('cotizacion:listar')

apps/cotizacion/views.py
# -*- COTIZACION -*-

from django.views.generic import ListView
from .models import Cotizacion
from django.shortcuts import render
from django.template import RequestContext
from django.views.generic import TemplateView
from apps.inicio.mixins import LoginRequiredMixin

class ListaCotizaciones(LoginRequiredMixin,ListView):
	model = Cotizacion
	context_object_name = 'lista_cotizaciones'



class PdfCreateView(LoginRequiredMixin,TemplateView):
	def get(self,request,*args,**kwargs):
		cotizacion= Cotizacion.objects.get(id=kwargs['pk'])
		context = {'cotizacion':cotizacion}

		return render(request, 'cotizacion/cotizacionPDF.html', context)
		

apps/cotizacion/templates/cotizacion/includes/crear.html
{% extends "base.html" %}
{% load static %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<!-- css auxiliar -->
{% block custom-css %}
	<!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
	<link href="{% static 'color_admin/assets/plugins/bootstrap-wizard/css/bwizard.min.css' %}" rel="stylesheet" />
	<!-- Para gestionar Fechas -->
	<link href="{% static 'color_admin/assets/plugins/bootstrap-datepicker/css/datepicker.css'%}" rel="stylesheet" />
 	<link href="{% static 'color_admin/assets/plugins/bootstrap-datepicker/css/datepicker3.css'%}" rel="stylesheet" />
 	<!-- fin Para gestionar Fechas -->

	<!-- ================== END PAGE LEVEL STYLE ================== -->
{% endblock %}

<!-- Enacabezado de la seccion -->
{% block content %}
	<!-- begin #page-container -->
	<div id="page-container" class="fade page-sidebar-fixed page-header-fixed">
		
		<!-- begin #header -->
		{% include "includes/header.html" %}
		<!-- end #header -->
		
		<!-- begin #sidebar -->
		{% include "includes/sidebar.html" %}
		<!-- end #sidebar -->
		
		<!-- begin #content -->
		<div id="content" class="content">
			<!-- begin page-header -->
			<h1 class="page-header">Cotizaciones</h1>
			<!-- end page-header -->
			
			<!-- begin indicators -->
			{% include "includes/indicadores.html"%}
			<!-- end indicators -->
						
			<!-- begin row -->
			<div class="row">

				<!-- begin col-8 -->
				<div class="col-md-8">
					<!-- begin col-12 -->
				    <div class="col-md-12">
				        <!-- begin panel -->
	                    <div class="panel panel-inverse">
	                        <div class="panel-heading">
	                            <div class="panel-heading-btn">
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
	                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
	                            </div>
	                            <h4 class="panel-title">Nueva cotización</h4>
	                        </div>
	                        <div class="panel-body">
	                        	{# Display a form #}
	                        	{# the enctype="multipart/form-data" is necessary to upload files#}
	                            <form action="{% url 'cotizacion:crear' %}" method="POST" enctype="multipart/form-data"> {% csrf_token %}
	                            {% bootstrap_form form %}
									<div id="wizard">
										
										<button type="submit" class="btn btn-inverse"><i class="fa fa-cog"></i> Generar</button>
										
										
									</div>
								</form>
	                        </div>
	                    </div>
	                    <!-- end panel -->
	                </div>
	                <!-- end col-12 -->
	            </div>
	            <!-- end col-8 -->

				<!-- begin col-4 -->
				<div class="col-md-4">
				{% include "includes/calendario.html" %}
				</div>
				<!-- end col-4 -->
			</div>
			<!-- end row -->
		</div>
		<!-- end #content -->
	
		
		<!-- begin scroll to top btn -->
		<a href="javascript:;" class="btn btn-icon btn-circle btn-success btn-scroll-to-top fade" data-click="scroll-top"><i class="fa fa-angle-up"></i></a>
		<!-- end scroll to top btn -->
	</div>
	<!-- end page container -->
{% endblock %}

<!-- JavaScript auxiliar -->
{% block custom-js %}
	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static 'color_admin/assets/plugins/bootstrap-wizard/js/bwizard.js' %}"></script>
	<script src="{% static 'color_admin/assets/js/form-wizards.demo.min.js' %}"></script>
	<script src="{% static 'color_admin/assets/js/apps.min.js' %}"></script>
	
	<!-- Para gestionar Fechas -->
	<script src="{% static 'color_admin/assets/js/bootstrap-datepicker.js' %}"></script>

	<script>
		$(document).ready(function(){
			$('#id_fecha').datepicker({todayHighlight:true,autoclose:true});
			$('#id_fecha_vencimiento').datepicker({todayHighlight:true,autoclose:true});

		});
	</script>
	<!-- fin Para gestionar Fechas -->

	<!-- ================== END PAGE LEVEL JS ================== -->
{% endblock %}