concesionario/urls.py
# -*- encoding: utf-8 -*-

from django.conf.urls import include, url
from django.contrib import admin
from concesionario import settings
from django.conf.urls.static import static

urlpatterns = [

	url(r'^admin/', admin.site.urls),
    url(r'', include(('apps.inicio.url','inicio'),namespace='inicio')),
    url(r'', include(('apps.cuenta.url','cuenta'),namespace='cuenta')),
    url(r'', include(('apps.cotizacion.url','cotizacion'),namespace='cotizacion')),
    url(r'', include(('apps.cliente.url','cliente'),namespace='cliente')),
    url(r'', include(('apps.empleado.url','empleado'),namespace='empleado')),
    url(r'', include(('apps.repuesto.url','repuesto'),namespace='repuesto')),
    url(r'', include(('apps.sucursal.url','sucursal'),namespace='sucursal')),
    url(r'', include(('apps.vehiculo.url','vehiculo'),namespace='vehiculo')),
    url(r'', include(('apps.venta.url','venta'),namespace='venta')),
    url(r'', include(('apps.proveedor.url','proveedor'),namespace='proveedor')),
    url(r'', include(('apps.reporte.url','reporte'),namespace='reporte')),
    url(r'', include(('apps.orden_de_trabajo.url','orden_de_trabajo'),namespace='orden_de_trabajo')),
    url(r'', include(('apps.cotizacion_orden_de_trabajo.url','cotizacion_orden_de_trabajo'),namespace='cotizacion_orden_de_trabajo')),
	url(r'', include(('apps.factura_orden_de_trabajo.url','factura_orden_de_trabajo'),namespace='factura_orden_de_trabajo')),
    url(r'', include(('apps.movil.url','movil'),namespace='movil')),

    #url para acceder a la imagenes que estan en la carpeta media del proyecto
    #se deseas colocar imagenes en tu contenido HTML, este link es necesario para que se muestren las imagenes
   

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/venta/models.py
# -*- encoding: utf-8 -*-

from django.db import models
from datetime import datetime
from apps.empleado.models import Empleado
from apps.cliente.models import Cliente
from apps.sucursal.models import SucursalVehiculo



# Forma de pago en que se realiza la compra
CREDITO = 'Credito'
EFECTIVO = 'Efectivo'
TARJETA_CREDITO = 'Tarjeta_credito'
TARJETA_DEBITO = 'Tarjeta_debito'

forma_pago_choices = (
	(CREDITO, 'Credito'),
	(EFECTIVO, 'Efectivo'),
	(TARJETA_CREDITO, 'Tarjeta de credito'),
	(TARJETA_DEBITO, 'Tarjeta de debito'),
)

class Venta(models.Model):
	"""Define como se organizaran las ventas en la base de datos."""
	#Llave foranea al empleado que realiza la venta
	empleado = models.ForeignKey(Empleado,related_name='ventas',on_delete=models.CASCADE)
	#Cliente que realiza la compra
	cliente = models.ForeignKey(Cliente,on_delete=models.CASCADE)
	#Vehiculo de la venta
	sucursal_vehiculo = models.ForeignKey(SucursalVehiculo,related_name='ventas',on_delete=models.CASCADE)
	#Fecha en que se realiza la venta
	fecha_venta=models.DateField(auto_now_add=True)
	#Precio final de la venta, precio vehiculo - descuento
	precio_venta = models.FloatField()
	#Forma de pago para la compra del vehiculo
	forma_pago = models.CharField(max_length=20, choices=forma_pago_choices, default=EFECTIVO)
	#Estado de la venta, Activa/inactiva
	habilitado = models.BooleanField(default = True)

	#Permite hacer modificaciones agregadas a la representacion del modelo
	class Meta:
		ordering = ['fecha_venta']
		verbose_name_plural = "Ventas"

	#Permite determinar una representacion en string del objeto empleado
	def __str__(self):
		return self.sucursal_vehiculo.sucursal.nombre + " " + self.sucursal_vehiculo.vehiculo.marca

	#Permite determinar una represetacion en string para el objeto (Esto es para versiones de Python 2)
	def __unicode__(self):
		return self.sucursal_vehiculo.sucursal.nombre + " " + self.sucursal_vehiculo.vehiculo.marca

	@staticmethod
	def dinero_acumulado(self):
		ventas = self.objects.all()
		total = 0
		for venta in ventas:
			total += venta.precio_venta
		return total

	def nombre_sucursal(self):
		return self.sucursal_vehiculo.sucursal.nombre

	def marca_vehiculo(self):
		return self.sucursal_vehiculo.vehiculo.marca

apps/venta/forms.py
# -*- encoding: utf-8 -*-
from django.urls import reverse_lazy, reverse
from django import forms
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.template import RequestContext
from django.views.generic.edit import CreateView, UpdateView
from .models import Venta
from apps.cliente.models import Cliente
from apps.empleado.models import Empleado
from apps.vehiculo.models import Vehiculo
from apps.sucursal.models import SucursalVehiculo
from apps.inicio.mixins import LoginRequiredMixin

class CrearVenta(LoginRequiredMixin, CreateView):
	model = Venta
	#precio_venta: no se incluye este campo en el formulario pero
	fields = ['cliente', 'sucursal_vehiculo', 'forma_pago']
	success_url = reverse_lazy('venta:listar')

	def get_context_data(self,**kwargs):
		# empleado logueado
		empleado = Empleado.objects.get(user_id=self.request.user.id)
		# sucursal del empleado
		sucursal = empleado.sucursal
		context = super(CrearVenta,self).get_context_data(**kwargs)
		context['search_button_text'] = 'Completar Formulario'
		clientes = Cliente.objects.all()
		context['lista_clientes'] = clientes
	  	

		sucursal_vehiculo = SucursalVehiculo.objects.filter(sucursal=sucursal)
		context['sucursal_vehiculos'] = sucursal_vehiculo
		return context

	def post(self, request, *args, **kwargs):

		empleado = Empleado.objects.get(user_id=self.request.user.id)
		cliente = Cliente.objects.get(pk=request.POST["cliente"])
		sucursal_vehiculo = SucursalVehiculo.objects.get(pk=request.POST["sucursal_vehiculo"])
		forma_pago = request.POST["forma_pago"]
		venta = Venta(empleado = empleado, cliente = cliente, sucursal_vehiculo = sucursal_vehiculo,
			precio_venta = sucursal_vehiculo.vehiculo.precio, forma_pago = forma_pago)
		venta.save()

		sucursal_vehiculo.cantidad = sucursal_vehiculo.cantidad-1
		sucursal_vehiculo.save()
		context = {'venta':venta}
		return render(request, 'venta/factura.html', context)

apps/venta/views.py
# -*- encoding: utf-8 -*-

from django.views.generic import ListView
from .models import Venta
from django.shortcuts import render
from django.template import RequestContext
from django.views.generic import TemplateView
from apps.inicio.mixins import LoginRequiredMixin

class ListaVentas(LoginRequiredMixin, ListView):
	model = Venta
	context_object_name = 'lista_ventas'


class FacturaCreateView(LoginRequiredMixin, TemplateView):
	def get(self,request,*args,**kwargs):
		venta= Venta.objects.get(id=kwargs['pk'])
		context = {'venta':venta}

		return render(request, 'venta/factura.html', context)

apps/venta/templates/venta/factura.html
{% extends "base.html" %}
{% load static %}
{% load factura_tags %}
{% block css %}
{{ block.super }}
  <link href="{% static 'color_admin/assets/css/invoice-print.min.css' %}" rel="stylesheet" />
{% endblock %}
{% block section_title %}{% endblock %}
{% block section_subtitle %}{% endblock %}
{% block content %}
            <!-- begin invoice -->
            <div class="invoice">

                <div class="row invoice-company">
                    <div class="row pull-left">
                      <img src="{{ MEDIA_URL }}imagenes/logo/logo1.jpg" height="70px" class="img">
                    </div>
                    <span class="pull-right hidden-print">
                      <a href="javascript:;" onclick="window.history.back()" class="btn btn-sm btn-success m-b-10"><i class="fa fa-arrow-circle-left"></i> Volver</a>
                      <a href="javascript:;" onclick="window.print()" class="btn btn-sm btn-success m-b-10"><i class="fa fa-print m-r-5"></i> Imprimir</a>
                    </span>
                </div>
                <div class="row invoice-header">
                    <div class="invoice-from">
                        <address class="m-t-5 m-b-5">
                            <strong> Matisa Autos SRL {{ user.empleado.sucursal.nombre }}.</strong><br />
                            {{ user.empleado.sucursal.direccion }}<br />
                            {{ user.empleado.sucursal.ciudad }}<br />
                            Telefono: (032) {{ user.empleado.sucursal.telefono }}<br />
                        </address>
                    </div>
                    <div class="invoice-to">
                        <small></small>
                        <address class="m-t-5 m-b-5">
                            <strong>{{ venta.cliente.nombre }} {{ venta.cliente.apellido }}</strong><br />
                            Direccion<br />
                            {{ venta.cliente.ciudad }}, {{ venta.cliente.departamento }}<br />
                            Telefono: (032) {{ venta.cliente.telefono }}<br />
                            Celular: {{ venta.cliente.celular }}
                        </address>                     
                    
                    </div>
                    <div class="invoice-date">
                        Fecha De Emisión:
                        <div class="date m-t-5">{% now 'SHORT_DATE_FORMAT' %}</div>
                        <div class="invoice-detail">
                            #Factura: {{ venta.id }}
                        </div>
                    </div>
                </div>
                <div class="invoice-content">
                    <div class="table-responsive">
                        <table class="table table-invoice">
                            <thead>
                                <tr>
                                    <th>DESCRIPCIÓN DE COMPRA</th>
                                    <th>CANTIDAD</th>
                                    <th>PRECIO</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td>
                                        
                                        <small> {{ venta.sucursal_vehiculo }}</small>
                                    </td>
                                    <td>1</td>
                                    <td>${{ venta.precio_venta}}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                    <div class="invoice-price">
                        <div class="invoice-price-left">
                            <div class="invoice-price-row">
                                <div class="sub-price">
                                    <small>SUBTOTAL</small>
                                   {{ venta.precio_venta}}
                                </div>
                              
                               
                            </div>
                        </div>
                        <div class="invoice-price-right">
                            <small>TOTAL</small> {{ venta.precio_venta}}
                        </div>
                    </div>
                </div>
               
                <div class="invoice-footer text-muted">
                    <p class="text-center m-b-5">
                       Sistema de Gestion de Inventario Automotriz
                    </p>
                    <p class="text-center">
                        <span class="m-r-10"><i class="fa fa-globe"></i> www.matisaautos.com</span>
                        <span class="m-r-10"><i class="fa fa-phone"></i> T:(2){{ user.empleado.sucursal.telefono }}</span>
                        <span class="m-r-10"><i class="fa fa-envelope"></i> {{ user.email }}</span>
                    </p>
                </div>
            </div>
            <!-- end invoice -->
{% endblock %}
{% block javascript %}
{{ block.super }}
{% endblock %}

apps/venta/templates/venta/venta_form.html
{% extends "base.html" %}
{% load static %}

{# Load the tag library #}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

{% block css %}
{{ block.super }}

       <!-- ================== BEGIN PAGE LEVEL STYLE ================== -->
    <link href="{% static 'color_admin/assets/plugins/bootstrap-wizard/css/bwizard.min.css' %}" rel="stylesheet" />
        <!-- Para gestionar Fechas -->
    <link href="{% static 'color_admin/assets/plugins/bootstrap-datepicker/css/datepicker.css'%}" rel="stylesheet" />
    <link href="{% static 'color_admin/assets/plugins/bootstrap-datepicker/css/datepicker3.css'%}" rel="stylesheet" />
    <!-- fin Para gestionar Fechas -->
    <!-- ================== END PAGE LEVEL STYLE ================== -->
{% endblock %}

{% block breadcrumb %}
Gestión de Ventas
{% endblock %}
{% block section_title %}Nueva Venta{{ section_title }}{% endblock %}
{% block section_subtitle %}Diligencie el siguiente formulario{% endblock %}
{% block content %}


    <!-- begin col-12 --><div class="row">
    <!-- begin col-12 -->
    <div class="col-md-12">
        <!-- begin panel -->
        <div class="panel panel-inverse">
            <div class="panel-heading">
                <div class="panel-heading-btn">
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                    <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                </div>Nueva Venta</h4>
            </div>
            <div class="panel-body">
                <form action="{{ request.path }}" method="POST" data-parsley-validate="true" name="form-wizard" enctype="multipart/form-data" >{% csrf_token %}
                    <div id="wizard">
                        <ol>
                            <li>
                                Cliente
                                <small>Seleccione el Cliente</small>
                            </li>
                            <li>
                                Vehículo
                                <small>Seleccione el Vehículo</small>
                            </li>
                            <li>
                                Información Adicional
                                <small></small>
                            </li>
                        </ol>
                        <!-- begin wizard step-1 -->
                        <div class="wizard-step-1">
                            <fieldset>
                                <div class="row">
                                    <div class="table-responsive">
                                    <table class="table table-striped table-bordered">
                                        <thead>
                                            <tr>
                                            <th>Identificación</th>
                                            <th>Nombre</th>
                                            <th>Apellido</th>
                                            <th>Ciudad</th>
                                            <th>Departamento</th>
                                            <th>Teléfono</th>
                                            <th>Celular</th>
                                            <th>Email</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% if lista_clientes %}
                                            {% for cliente  in lista_clientes %}
                                            <tr>
                                                <td><a class="clienteID" name="{{cliente.pk}}"> {{ cliente.identificacion }}</a></td>
                                                <td>{{ cliente.nombre }}</td>
                                                <td>{{ cliente.apellido }}</td>
                                                <td>{{ cliente.ciudad }}</td>
                                                <td>{{ cliente.departamento }}</td>
                                                <td>{{ cliente.telefono }}</td>
                                                <td>{{ cliente.celular }}</td>
                                                <td>{{ cliente.email }}</td>
                                            {% endfor %}
                                        {% else %}
                                        <p><h2>No hay Clientes registrados.</h2></p>
                                            {% endif %}
                                        </tbody>
                                    </table>
                                </div>

                                </div>
                            </fieldset>
                        </div>

                        <div class="wizard-step-2">
                            <fieldset>
                                <div class="row">

                                <div class="panel-body">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-bordered">
                                            <thead>
                                                <tr>
                                                    <th>Marca</th>
                                                    <th>Modelo</th>
                                                    <th>Precio</th>
                                                    <th>Color</th>
                                                    <th>Cantidad</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% for sucursal_vehiculo in sucursal_vehiculos %}
                                                <tr>

                                                    <td><a class="suc_vehiculoID" name="{{sucursal_vehiculo.pk}}"> {{ sucursal_vehiculo.vehiculo.marca }}</td>
                                                    <td>{{ sucursal_vehiculo.vehiculo.modelo }}</td>
                                                    <td>{{ sucursal_vehiculo.vehiculo.precio }}</td>
                                                    <td>{{ sucursal_vehiculo.color }}</td>
                                                    <td>{{ sucursal_vehiculo.cantidad }}</td>
                                                </tr >
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                                </div>
                            </fieldset>
                        </div>
                        <!-- end wizard step-2 -->

                        <div class="wizard-step-3">
                            <fieldset>
                                <div class="row">
                                  <div class="col-md-8 col-md-offset-2">
                                      {% bootstrap_form form %}
                                      <div class="pull-right" >
                                          <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-cog"></i> Guardar</button>
                                      </div>
                                  </div>
                                  </div>
                                </fieldset>
                        </div>
                        <!-- end wizard step-1 -->
                    </div>

                </form>
            </div>
        </div>
        <!-- end panel -->
    </div>
    <!-- end col-12 -->
</div>
<!-- end row -->
            <!-- end row -->
{% endblock %}

{% block javascript %}
{{ block.super }}
<!-- ================== BEGIN PAGE LEVEL JS ================== -->
<!-- Para funcionamiento de tablas -->
<script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/data-table.js' %}"></script>

<script src="{% static 'color_admin/assets/plugins/parsley/dist/parsley.js' %}"></script>
<script src="{% static 'color_admin/assets/plugins/bootstrap-wizard/js/bwizard.js' %}"></script>
<script src="{% static 'color_admin/assets/js/form-wizards-validation.demo.min.js' %}"></script>
<script src="{% static 'color_admin/assets/js/apps.min.js' %}"></script>
<script src="{% static 'color_admin/assets/js/bootstrap-datepicker.js' %}"></script>
<script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/jquery.dataTables.js' %}"></script>
<script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/data-table.js' %}"></script>
<!-- ================== END PAGE LEVEL JS ================== -->
<script>
    $(document).ready(function() {
        FormWizardValidation.init();
        // $("#id_empleado").attr('readonly','readonly');
        // $("#id_cliente").attr('readonly','readonly');
        // $("#id_vehiculo").attr('readonly','readonly');

        $(".clienteID").click( function (event){
            event.preventDefault();
            var clickedClienteId = $(this).attr('name');
            $("#id_cliente").val(clickedClienteId);
            $(".next").click();
        });
        $(".suc_vehiculoID").click( function (event){
            event.preventDefault();
            var clickedVehiculoId = $(this).attr('name');
            $("#id_sucursal_vehiculo").val(clickedVehiculoId);
            $(".next").click();
        });

    });
</script>

{% endblock %}

apps/venta/templates/venta/venta_list.html
{% extends "base.html" %}
{% load static %}
 
{% block css %}
{{ block.super }}
    <link href="{% static 'color_admin/assets/plugins/DataTables-1.9.4/css/data-table.css' %}" rel="stylesheet" />
{% endblock %}
{% block breadcrumb %}
Gestion de Ventas
{% endblock %} 
{% block section_title %}Ventas{% endblock %}
{% block section_subtitle %}Seleccione la Venta que desea ver{% endblock %}
{% block content %}
                <!-- begin col-12 -->
                <div class="col-md-12">
                    

                    <!-- begin panel -->
                    <div class="panel panel-inverse">
                        <div class="panel-heading">
                            <div class="panel-heading-btn">
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-repeat"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
                                <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
                            </div>
                            <h4 class="panel-title">Ventas</h4>
                        </div>
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table id="data-table" class="table table-striped table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Número de Factura</th>
                                            <th>Cliente</th>
                                            <th>Vehiculo</th>
                                            <th>Fecha de Venta</th>
                                            <th>Precio Venta</th>
                                            <th>Forma Pago</th> </tr>
                                    </thead>
                       {% if lista_ventas %} 
                                            {% for venta  in lista_ventas %}
                                                <tr>
                                                    <td><a href="{% url 'venta:factura' venta.pk %}">{{ venta.pk }}</td>
                                                    <td>{{ venta.cliente}}</a></td>
                                                    <td>{{ venta.sucursal_vehiculo }}</td>
                                                    <td>{{ venta.fecha_venta }}</td>
                                                    <td>{{ venta.precio_venta }}</td>
                                                    <td>{{ venta.forma_pago }}</td>
                                                </tr >
                                            {% endfor %} 
                                            </ul> 
                                            {% else %} 
                                                <p><h2>No hay Ventas registradas.</h2></p>
                                        {% endif %} 
                                    </tbody>
                                             </table>
                            </div>
                        </div>
                    </div>
                    <!-- end panel -->
                </div>
                <!-- end col-12 --> 
{% endblock %}

{% block javascript %}
{{ block.super }}

    <!-- ================== BEGIN PAGE LEVEL JS TABLE ================== -->
    <script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'color_admin/assets/plugins/DataTables-1.9.4/js/data-table.js' %}"></script>
    <script src="{% static 'color_admin/assets/js/apps.min.js' %}"></script>
    <script src="{% static 'color_admin/assets/js/inbox.demo.min.js' %}"></script>
    <script src="{% static 'color_admin/assets/js/apps.min.js' %}"></script>
    <!-- ================== END PAGE LEVEL JS ================== -->

{% endblock %}